###
GET http://localhost:8080/hello

###
GET  http://localhost:8080/products


###

POST http://localhost:8080/products HTTP/1.1
content-type: application/json

{
    "id":"1",
    "name": "Telewizor",
    "description": "Telewizor plazmowy123",
    "price": 5000
}

###
DELETE http://localhost:8080/products/1 HTTP/1.1
###
PUT http://localhost:8080/products/ 
content-type: application/json

{
    "id":"1",
    "name":"Telewizor 58",
    "description":"Telewizor plazmowy zmieniony",
    "price":500
}





###
GET  http://localhost:8080/categories  HTTP/1.1

###

POST http://localhost:8080/categories 
content-type: application/json

{
    "id":"2",
    "name": "Myszki komputerowe",
    "quantity": 220
    
}

###
DELETE http://localhost:8080/categories/2 
###
PUT http://localhost:8080/categories/ 
content-type: application/json

{
    "id":"2",
    "name": "Myszki komputerowe zmienone",
    "quantity":250
    
}